/**
 * Centralised route names. Screens never use string literals for navigation.
 */
export const Routes = {
  // Root / auth
  Splash: 'Splash',
  Login: 'Login',
  ResetPassword: 'ResetPassword',
  Forbidden: 'Forbidden',
  DevGallery: 'DevGallery',
  // Shells
  StudentTabs: 'StudentTabs',
  InstructorTabs: 'InstructorTabs',
  // Student tabs
  StudentHomeTab: 'StudentHomeTab',
  StudentCoursesTab: 'StudentCoursesTab',
  StudentScheduleTab: 'StudentScheduleTab',
  StudentMessagesTab: 'StudentMessagesTab',
  StudentProfileTab: 'StudentProfileTab',
  // Instructor tabs
  InstructorHomeTab: 'InstructorHomeTab',
  InstructorCoursesTab: 'InstructorCoursesTab',
  InstructorGradesTab: 'InstructorGradesTab',
  InstructorMessagesTab: 'InstructorMessagesTab',
  InstructorMoreTab: 'InstructorMoreTab',
  // Student – catalogue & learning
  StudentCatalogue: 'StudentCatalogue',
  StudentProgrammeDetails: 'StudentProgrammeDetails',
  StudentCheckout: 'StudentCheckout',
  StudentMyLearning: 'StudentMyLearning',
  StudentOutline: 'StudentOutline',
  StudentReading: 'StudentReading',
  StudentLecture: 'StudentLecture',
  StudentPracticeQuiz: 'StudentPracticeQuiz',
  StudentMatching: 'StudentMatching',
  StudentAssessment: 'StudentAssessment',
  StudentCourseComplete: 'StudentCourseComplete',
  StudentCertificate: 'StudentCertificate',
  StudentAskCoach: 'StudentAskCoach',
  // Student – enrolled courses
  StudentMyCourses: 'StudentMyCourses',
  StudentCourseDetails: 'StudentCourseDetails',
  StudentLearningObjectives: 'StudentLearningObjectives',
  StudentCourseInfo: 'StudentCourseInfo',
  StudentLiveRoom: 'StudentLiveRoom',
  StudentCourseQuiz: 'StudentCourseQuiz',
  StudentAssignments: 'StudentAssignments',
  StudentAssignmentDetails: 'StudentAssignmentDetails',
  StudentAttendance: 'StudentAttendance',
  StudentWorkshops: 'StudentWorkshops',
  StudentWorkshopDetails: 'StudentWorkshopDetails',
  // Student – records
  StudentFinalMarks: 'StudentFinalMarks',
  StudentBadges: 'StudentBadges',
  StudentExtracurricular: 'StudentExtracurricular',
  StudentProgramPlan: 'StudentProgramPlan',
  StudentRequiredTasks: 'StudentRequiredTasks',
  StudentDocuments: 'StudentDocuments',
  StudentTaxDocuments: 'StudentTaxDocuments',
  StudentFinance: 'StudentFinance',
  StudentTransactions: 'StudentTransactions',
  StudentPayBalance: 'StudentPayBalance',
  StudentLeave: 'StudentLeave',
  StudentRequestDetails: 'StudentRequestDetails',
  StudentPersonalDetails: 'StudentPersonalDetails',
  StudentSecurity: 'StudentSecurity',
  StudentChangePassword: 'StudentChangePassword',
  StudentEnglishTest: 'StudentEnglishTest',
  StudentEnglishTestRegister: 'StudentEnglishTestRegister',
  StudentProfile: 'StudentProfile',
  StudentServices: 'StudentServices',
  StudentSupport: 'StudentSupport',
  // Shared
  TimeZone: 'TimeZone',
  Notifications: 'Notifications',
  Mail: 'Mail',
  MailCompose: 'MailCompose',
  MailMessage: 'MailMessage',
  AskHeritage: 'AskHeritage',
  FileViewer: 'FileViewer',
  // Instructor
  InstructorDashboard: 'InstructorDashboard',
  InstructorAiDraft: 'InstructorAiDraft',
  InstructorEditLesson: 'InstructorEditLesson',
  InstructorLessonPreview: 'InstructorLessonPreview',
  InstructorStudentList: 'InstructorStudentList',
  InstructorStudentProfile: 'InstructorStudentProfile',
  InstructorMyCourses: 'InstructorMyCourses',
  InstructorCourseWorkspace: 'InstructorCourseWorkspace',
  InstructorMarkAttendance: 'InstructorMarkAttendance',
  InstructorGradeEntry: 'InstructorGradeEntry',
  InstructorCourseAttendance: 'InstructorCourseAttendance',
  InstructorEvaluations: 'InstructorEvaluations',
  InstructorEvaluationDetails: 'InstructorEvaluationDetails',
  InstructorRepository: 'InstructorRepository',
  InstructorCreateContentCourse: 'InstructorCreateContentCourse',
  InstructorRepositoryHistory: 'InstructorRepositoryHistory',
  InstructorPendingSchedules: 'InstructorPendingSchedules',
  InstructorScheduleReview: 'InstructorScheduleReview',
  InstructorGradesSubmission: 'InstructorGradesSubmission',
  InstructorCourseHistory: 'InstructorCourseHistory',
  InstructorCourseHistoryDetails: 'InstructorCourseHistoryDetails',
  InstructorWorkshopEnrolments: 'InstructorWorkshopEnrolments',
  InstructorWorkshopDetails: 'InstructorWorkshopDetails',
  InstructorFaculties: 'InstructorFaculties',
  InstructorAddFaculty: 'InstructorAddFaculty',
  InstructorAddProgram: 'InstructorAddProgram',
  InstructorProgramTypes: 'InstructorProgramTypes',
  InstructorManageTerms: 'InstructorManageTerms',
  InstructorTermForm: 'InstructorTermForm',
  InstructorProfile: 'InstructorProfile',
  InstructorMore: 'InstructorMore',
  InstructorLiveRoom: 'InstructorLiveRoom',
} as const;

export type RouteName = (typeof Routes)[keyof typeof Routes];
